name: Deployment

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2
      - uses: docker://aergus/latex
      - name: Install LyX
      - run: apt-get install lyx fonts-lyx
      - name: Build PDF notes
        run: make all

  release:
    name: Release
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: docker://aergus/latex
      - name: Install LyX
      - run: apt-get install lyx fonts-lyx
      - name: Build PDF notes
        run: make all
