name: Deployment

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'

jobs:
  check:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2

  release:
    name: Release
    if: github.ref == 'refs/heads/master'
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LyX and Latex dependencies
        run: make install
      - name: Build PDF notes
        run: make all
