name: lyx-notes-deployment

on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*.*.*'

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: LaTeX linter
        uses: colinaaa/chktex-action@v1.1.2

  release:
    name: Release
    if: github.ref == 'refs/heads/master'
    needs: [check]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install LyX and Latex dependencies
        run: make install
      - name: Build PDF notes
        run: make all
      - uses: actions/upload-artifact@v2
        with:
          name: PDF Artifacts
          path: pdfs/*.pdf
